//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCPersonEF.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;


    public enum Gender
    {
        Male, Female, NA
    }


    public partial class People
    {
        public System.Guid Id { get; set; }

        [Required]
        [StringLength(50, MinimumLength =2)]
        [RegularExpression(@"^[A-Za-z -.]{2,50}$")]
        public string Name { get; set; }

        [Range(0,130)]
        public int Age { get; set; }

        [RegularExpression(@"^[A-Z][0-9][A-Z] ?[0-9][A-Z][0-9]$")]
        public string PostalCode { get; set; }

        
        //[EnumDataType]
        public string Gender { get; set; }

        [DataType(DataType.Date)]
        public System.DateTime BirthDate { get; set; }
    }
}
