//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACME.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Products
    {
        public int ProductId { get; set; }
        [Required]
        [StringLength(20, MinimumLength =2)]
        public string Name { get; set; }
        [Range(0.0, 10000.0)]
        public decimal Price { get; set; }
    }
}
