//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quiz2MVCEF.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Travel
    {
        [Key]
        public int Id { get; set; }


        [Required]
        [StringLength(50, MinimumLength =2)]
        [RegularExpression(@"^[A-Za-z -.]{2,50}$")]
        public string Name { get; set; }


        [Required]
        [Range(1, 150)]
        public int Age { get; set; }

                
        [RegularExpression(@"^[A-Z]{2}[0-9]{6}$")]
        public string PassportNo { get; set; }


        [Required]
        [DataType(DataType.Date)]
        public System.DateTime Departure { get; set; }


        [Required]
        [DataType(DataType.Date)]
        public System.DateTime Arrival { get; set; }


        [Required]
        [RegularExpression(@"^[A-Z]{3}$")]
        public string FromAirport { get; set; }


        [Required]
        [RegularExpression(@"^[A-Z]{3}$")]
        public string ToAirport { get; set; }


        [Required]
        public string ComfortClass { get; set; }


        public IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
        {
            if (Arrival < Departure)
            {
                yield return
                  new ValidationResult(errorMessage: "Arrival date must be after departure date.",
                                       memberNames: new[] { "Arrival" });
            }
        }
    }

    enum ComfortClass
    {
        Economy, EconomyPlus, Premium, Business
    }
}
